POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/ec15dff9-5c07-464a-85b9-a783cb403df6/attendees
Content-Type: application/json

{
  "name": "Kauan Soares",
  "email": "gbskauan@gmail.com"
}

###

GET http://localhost:3333/events/ec15dff9-5c07-464a-85b9-a783cb403df6

###

GET http://localhost:3333/attendees/9/badge

###

GET http://localhost:3333/attendees/8/check-in

###

GET http://localhost:3333/events/ec15dff9-5c07-464a-85b9-a783cb403df6/attendees
